version: '3.3'

services:
  vite-react-app:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_IMG_URL=${VITE_IMG_URL}
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_IMG_URL=${VITE_IMG_URL}
    restart: unless-stopped

networks:
  default:
    external: false