version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_IMG_URL: ${VITE_IMG_URL}
    container_name: vite-react-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env