version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map to standard HTTP port
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    external: true
