version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - VITE_API_URL=https://api.autoshop.samarkandcargo.com/api
      - VITE_IMG_URL=https://autoshop.fra1.cdn.digitaloceanspaces.com/
    restart: unless-stopped