version: "3.3"
services:
  react-app:
    build: .
    ports:
      - "5173:5173"  # Serve on standard HTTP port in production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge